Made direnv-setup work with existing .envrc files

diff --git a/local/bin/direnv-setup b/local/bin/direnv-setup
--- a/local/bin/direnv-setup
+++ b/local/bin/direnv-setup
@@ -2,30 +2,47 @@
 
 envpath="$PWD/.envrc"
 
+exists=0
 if [ -f "$envpath" ]; then
-	echo >&2 "There already is a direnv config file at '$envpath'."
-	exit 1
+	exists=1
+	echo "There already is a direnv config file at '$envpath', appending missing lines to the end."
 fi
 
+changes=0
+addline() {
+	if ! grep -qxF "$1" "$envpath"; then
+		if [ "$exists" -eq 1 ] && [ "$changes" -eq 0 ]; then
+			echo >> "$envpath"
+		fi
+		: $((changes++))
+		echo "$1" >> "$envpath"
+	fi
+}
+
 if [ -f "shell.nix" ]; then
-	echo "use nix" >> "$envpath"
+	addline "use nix"
 fi
 if [ -f "flake.nix" ]; then
-	echo "use flake" >> "$envpath"
+	addline "use flake"
 fi
 
 if [ -f "Pipfile" ]; then
-	echo "layout pipenv" >> "$envpath"
+	addline "layout pipenv"
 fi
 if [ -f "pyproject.toml" ] && grep -q "poetry" "pyproject.toml"; then
-	echo "layout poetry" >> "$envpath"
+	addline "layout poetry"
 fi
 
-if [ ! -s "$envpath" ]; then
+if [ "$changes" -eq 0 ]; then
 	echo >&2 "No environment files were recognized, aborting."
 	exit 1
 fi
-echo "Created direnv config file at '$envpath'."
+
+if [ "$exists" -eq 0 ]; then
+	echo "Created direnv config file at '$envpath'."
+else
+	echo "Updated direnv config file at '$envpath'."
+fi
 
 direnv allow "$envpath"
 direnv reload
