Add pipenv/poetry support to direnv

diff --git a/local/bin/direnv-setup b/local/bin/direnv-setup
--- a/local/bin/direnv-setup
+++ b/local/bin/direnv-setup
@@ -7,11 +7,20 @@ if [ -f "$envpath" ]; then
 	exit 1
 fi
 
-if [ ! -f ".tool-versions" ]; then
-	echo >&2 "There is no .tool-versions file, might want to fix that."
+if [ -f ".tool-versions" ]; then
+	echo "use asdf" >> "$envpath"
+fi
+if [ -f "Pipfile" ]; then
+	echo "layout pipenv" >> "$envpath"
+fi
+if [ -f "pyproject.toml" ] && grep -q "poetry" "pyproject.toml"; then
+	echo "layout poetry" >> "$envpath"
 fi
 
-echo "use asdf" > "$envpath"
+if [ ! -s "$envpath" ]; then
+	echo >&2 "No environment files were recognized, aborting."
+	exit 1
+fi
 echo "Created direnv config file at '$envpath'."
 
 asdf exec direnv allow "$envpath"
